### ISSUE TITLE
(*) Структура проекта + сценарий сборки

### ISSUE THREAD

**Issue by avasyukov** [Aleksei-Anotskii/Tree_on_C-#3]
*Это пункт на отл. Но весь остальной код явно был написан не для того, чтобы сдаться на хор в итоге.*

Это материал семинара в середине семестра (базовый сценарий, см. https://github.com/avasyukov/mipt-cs-cpp-demos/tree/master/lab03) или последней лекции (небазовый сценарий, см. https://github.com/avasyukov/oop-2nd-term/tree/master/2019/lection1x)

Если тезисно:
- дерево должно жить отдельно (хэдер + реализация - пара файлов .cpp + .hpp/.h), интерфейс Container отдельно (вероятно, только .hpp/.h), работающий со всем этим прикладной код отдельно (условный main.cpp)
- в хэдерах (.hpp/.h) должно быть только объявление сущностей, вся их реализация должна быть в .cpp
- не стоит растаскивать логически одну сущность (дерево) на кучу файлов по паре функций в файле (если есть предметный ответ на вопрос "зачем?" - пусть будет, но просто так - не надо)
- ко всему этому нужен сценарий сборки CMake-ом (который позволит модельному коллеге собрать ваш проект хоть на Windows, хоть на Linux, хоть на MacOS, какой бы компилятор коллега ни использовал)

**Comment by Aleksei-Anotskii** [comment]
Изменения:
1. решил проблему с потерей памяти (при удалении я забывал освобождать память структуры, которую не использовал)
2. перекинул метод в приватный.

По структуре проекта, не особо понял, что вы имели ввиду, уточню это завтра на паре

**Comment by Aleksei-Anotskii** [comment]
Оформил, но он мне почему-то постоянно пишет что я ссылаюсь на какой-то "внешний символ"
В чём может быть ошибка?

**Comment by avasyukov** [comment]
Нужны подробности - текущий вид кода, какие действия делаете, что конкретно случается. Я не умею телепатически.

**Comment by avasyukov** [comment]
Обсудили, закрываем.
